// Generated by CoffeeScript 1.4.0
(function() {
  var CustomError, Main, action, colors, pkginfo, program, run, util;

  Main = require('./Main');

  CustomError = require('./CustomError');

  util = require('util');

  colors = require('colors');

  pkginfo = require('pkginfo');

  program = require('commander');

  colors.setTheme({
    error: 'red'
  });

  Object.defineProperty(String.prototype, 'maybe', {
    get: function() {
      if (typeof options !== "undefined" && options !== null ? options.color : void 0) {
        return this;
      } else {
        return this.stripColors;
      }
    }
  });

  /*
  *
  */


  run = function() {
    try {
      pkginfo(module);
    } catch (err) {
      util.puts("ERROR: Parsing eyes-cli/package.json".error.maybe);
      throw err;
    }
    program.version(module.exports.version).usage('[options] <file ...>').option('--no-pretty', 'no pretty formatting').option('--no-color', 'no color').option('-m, --max-length <n>', "max length", parseInt);
    program.parse(process.argv);
    action();
  };

  /*
  *
  */


  action = function() {
    var main, options;
    options = {};
    options.color = program.color;
    options.pretty = program.pretty;
    if (program.maxLength != null) {
      options.maxLength = program.maxLength;
    }
    try {
      main = new Main(options);
      main.command(program.args);
    } catch (err) {
      switch (true) {
        case err instanceof CustomError:
          util.puts(("ERROR: " + err.message).error.maybe);
          program.outputHelp();
          process.exit(1);
          break;
        case err instanceof SyntaxError:
          util.puts("ERROR: Invalid JSON".error.maybe);
          throw err;
          break;
        default:
          throw err;
      }
    }
  };

  exports.run = run;

}).call(this);
