// Generated by CoffeeScript 1.4.0

/*
* A custom error. Doesn't do much.
*/


(function() {
  var CustomError,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  CustomError = (function(_super) {

    __extends(CustomError, _super);

    function CustomError(msg) {
      var err;
      err = new Error();
      this.name = 'MyError';
      this.message = msg || err.message;
    }

    return CustomError;

  })(Error);

  module.exports = CustomError;

}).call(this);
